
FROM continuumio/anaconda
RUN conda install mpl_toolkits
RUN conda install -c conda-forge ipyleaflet
RUN conda install lxml
RUN pip install cesiumpy
RUN pip install pykml
RUN pip install -e git+git@github.com:clawpack/clawpack.git@v5.3.1#egg=clawpack
